-- Rename all multi-word columns and all tables to snake_case.
-- Uses ALTER TABLE ... RENAME to preserve existing data (Prisma's autogenerated
-- diff would DROP/CREATE and lose rows). PostgreSQL cascades renames to indexes,
-- constraints and foreign keys automatically.

-- DomainConfig -> domain_config
ALTER TABLE "DomainConfig" RENAME COLUMN "domainName" TO "domain_name";
ALTER TABLE "DomainConfig" RENAME COLUMN "domainVersion" TO "domain_version";
ALTER TABLE "DomainConfig" RENAME COLUMN "tagSet" TO "tag_set";
ALTER TABLE "DomainConfig" RENAME COLUMN "createdAt" TO "created_at";
ALTER TABLE "DomainConfig" RENAME COLUMN "approvedBy" TO "approved_by";
ALTER TABLE "DomainConfig" RENAME COLUMN "approvedAt" TO "approved_at";
ALTER TABLE "DomainConfig" RENAME TO "domain_config";

-- DimensionDefinition -> dimension_definition
ALTER TABLE "DimensionDefinition" RENAME COLUMN "domainConfigId" TO "domain_config_id";
ALTER TABLE "DimensionDefinition" RENAME TO "dimension_definition";

-- ProfileDefinition -> profile_definition
ALTER TABLE "ProfileDefinition" RENAME COLUMN "domainConfigId" TO "domain_config_id";
ALTER TABLE "ProfileDefinition" RENAME COLUMN "technicalDepth" TO "technical_depth";
ALTER TABLE "ProfileDefinition" RENAME TO "profile_definition";

-- WarrantDefinition -> warrant_definition
ALTER TABLE "WarrantDefinition" RENAME COLUMN "domainConfigId" TO "domain_config_id";
ALTER TABLE "WarrantDefinition" RENAME COLUMN "dimensionId" TO "dimension_id";
ALTER TABLE "WarrantDefinition" RENAME COLUMN "structuralWarrant" TO "structural_warrant";
ALTER TABLE "WarrantDefinition" RENAME TO "warrant_definition";

-- VetoDefinition -> veto_definition
ALTER TABLE "VetoDefinition" RENAME COLUMN "domainConfigId" TO "domain_config_id";
ALTER TABLE "VetoDefinition" RENAME COLUMN "evaluationRule" TO "evaluation_rule";
ALTER TABLE "VetoDefinition" RENAME COLUMN "remediationPath" TO "remediation_path";
ALTER TABLE "VetoDefinition" RENAME TO "veto_definition";

-- ConflictDefinition -> conflict_definition
ALTER TABLE "ConflictDefinition" RENAME COLUMN "domainConfigId" TO "domain_config_id";
ALTER TABLE "ConflictDefinition" RENAME COLUMN "dimensionAId" TO "dimension_a_id";
ALTER TABLE "ConflictDefinition" RENAME COLUMN "dimensionBId" TO "dimension_b_id";
ALTER TABLE "ConflictDefinition" RENAME COLUMN "conditionA" TO "condition_a";
ALTER TABLE "ConflictDefinition" RENAME COLUMN "conditionB" TO "condition_b";
ALTER TABLE "ConflictDefinition" RENAME TO "conflict_definition";

-- ArtifactVariable -> artifact_variable
ALTER TABLE "ArtifactVariable" RENAME COLUMN "domainConfigId" TO "domain_config_id";
ALTER TABLE "ArtifactVariable" RENAME COLUMN "extractionHint" TO "extraction_hint";
ALTER TABLE "ArtifactVariable" RENAME COLUMN "mapsToQuestionId" TO "maps_to_question_id";
ALTER TABLE "ArtifactVariable" RENAME TO "artifact_variable";

-- Project -> project
ALTER TABLE "Project" RENAME COLUMN "domainConfigId" TO "domain_config_id";
ALTER TABLE "Project" RENAME COLUMN "createdAt" TO "created_at";
ALTER TABLE "Project" RENAME COLUMN "updatedAt" TO "updated_at";
ALTER TABLE "Project" RENAME TO "project";

-- Collaborator -> collaborator
ALTER TABLE "Collaborator" RENAME COLUMN "projectId" TO "project_id";
ALTER TABLE "Collaborator" RENAME COLUMN "profileId" TO "profile_id";
ALTER TABLE "Collaborator" RENAME COLUMN "joinedAt" TO "joined_at";
ALTER TABLE "Collaborator" RENAME TO "collaborator";

-- Profile -> profile
ALTER TABLE "Profile" RENAME COLUMN "identificationMethod" TO "identification_method";
ALTER TABLE "Profile" RENAME COLUMN "createdAt" TO "created_at";
ALTER TABLE "Profile" RENAME COLUMN "updatedAt" TO "updated_at";
ALTER TABLE "Profile" RENAME TO "profile";

-- Session -> session
ALTER TABLE "Session" RENAME COLUMN "projectId" TO "project_id";
ALTER TABLE "Session" RENAME COLUMN "xstateSnapshot" TO "xstate_snapshot";
ALTER TABLE "Session" RENAME COLUMN "startedAt" TO "started_at";
ALTER TABLE "Session" RENAME COLUMN "completedAt" TO "completed_at";
ALTER TABLE "Session" RENAME TO "session";

-- QuestionTemplate -> question_template
ALTER TABLE "QuestionTemplate" RENAME COLUMN "domainConfigId" TO "domain_config_id";
ALTER TABLE "QuestionTemplate" RENAME COLUMN "targetProfiles" TO "target_profiles";
ALTER TABLE "QuestionTemplate" RENAME COLUMN "textPt" TO "text_pt";
ALTER TABLE "QuestionTemplate" RENAME COLUMN "textEn" TO "text_en";
ALTER TABLE "QuestionTemplate" RENAME COLUMN "textByProfile" TO "text_by_profile";
ALTER TABLE "QuestionTemplate" RENAME COLUMN "inputType" TO "input_type";
ALTER TABLE "QuestionTemplate" RENAME COLUMN "isCriticalForArgument" TO "is_critical_for_argument";
ALTER TABLE "QuestionTemplate" RENAME COLUMN "isEntryNode" TO "is_entry_node";
ALTER TABLE "QuestionTemplate" RENAME TO "question_template";

-- QuestionTemplateEdge -> question_template_edge
ALTER TABLE "QuestionTemplateEdge" RENAME COLUMN "sourceTemplateId" TO "source_template_id";
ALTER TABLE "QuestionTemplateEdge" RENAME COLUMN "targetTemplateId" TO "target_template_id";
ALTER TABLE "QuestionTemplateEdge" RENAME COLUMN "profileTypes" TO "profile_types";
ALTER TABLE "QuestionTemplateEdge" RENAME TO "question_template_edge";

-- QuestionInstance -> question_instance
ALTER TABLE "QuestionInstance" RENAME COLUMN "sessionId" TO "session_id";
ALTER TABLE "QuestionInstance" RENAME COLUMN "templateId" TO "template_id";
ALTER TABLE "QuestionInstance" RENAME COLUMN "parentInstanceId" TO "parent_instance_id";
ALTER TABLE "QuestionInstance" RENAME COLUMN "generatedByLLM" TO "generated_by_llm";
ALTER TABLE "QuestionInstance" RENAME COLUMN "llmPromptUsed" TO "llm_prompt_used";
ALTER TABLE "QuestionInstance" RENAME COLUMN "textShown" TO "text_shown";
ALTER TABLE "QuestionInstance" RENAME COLUMN "inputType" TO "input_type";
ALTER TABLE "QuestionInstance" RENAME COLUMN "createdAt" TO "created_at";
ALTER TABLE "QuestionInstance" RENAME COLUMN "skippedAt" TO "skipped_at";
ALTER TABLE "QuestionInstance" RENAME TO "question_instance";

-- Answer -> answer
ALTER TABLE "Answer" RENAME COLUMN "sessionId" TO "session_id";
ALTER TABLE "Answer" RENAME COLUMN "questionInstanceId" TO "question_instance_id";
ALTER TABLE "Answer" RENAME COLUMN "collaboratorId" TO "collaborator_id";
ALTER TABLE "Answer" RENAME COLUMN "delegatedTo" TO "delegated_to";
ALTER TABLE "Answer" RENAME COLUMN "epistemicConfidence" TO "epistemic_confidence";
ALTER TABLE "Answer" RENAME COLUMN "answeredAt" TO "answered_at";
ALTER TABLE "Answer" RENAME COLUMN "artifactExtractionId" TO "artifact_extraction_id";
ALTER TABLE "Answer" RENAME COLUMN "generatedByLLM" TO "generated_by_llm";
ALTER TABLE "Answer" RENAME TO "answer";

-- GitConnection -> git_connection
ALTER TABLE "GitConnection" RENAME COLUMN "projectId" TO "project_id";
ALTER TABLE "GitConnection" RENAME COLUMN "gitRepoUrl" TO "git_repo_url";
ALTER TABLE "GitConnection" RENAME COLUMN "commitSha" TO "commit_sha";
ALTER TABLE "GitConnection" RENAME COLUMN "connectedAt" TO "connected_at";
ALTER TABLE "GitConnection" RENAME COLUMN "lastSyncAt" TO "last_sync_at";
ALTER TABLE "GitConnection" RENAME TO "git_connection";

-- Artifact -> artifact
ALTER TABLE "Artifact" RENAME COLUMN "projectId" TO "project_id";
ALTER TABLE "Artifact" RENAME COLUMN "gitConnectionId" TO "git_connection_id";
ALTER TABLE "Artifact" RENAME COLUMN "filePath" TO "file_path";
ALTER TABLE "Artifact" RENAME COLUMN "storageKey" TO "storage_key";
ALTER TABLE "Artifact" RENAME COLUMN "storageBucket" TO "storage_bucket";
ALTER TABLE "Artifact" RENAME COLUMN "storageSizeBytes" TO "storage_size_bytes";
ALTER TABLE "Artifact" RENAME COLUMN "mimeType" TO "mime_type";
ALTER TABLE "Artifact" RENAME COLUMN "analysisStatus" TO "analysis_status";
ALTER TABLE "Artifact" RENAME COLUMN "createdAt" TO "created_at";
ALTER TABLE "Artifact" RENAME COLUMN "analyzedAt" TO "analyzed_at";
ALTER TABLE "Artifact" RENAME TO "artifact";

-- ArtifactExtraction -> artifact_extraction
ALTER TABLE "ArtifactExtraction" RENAME COLUMN "artifactId" TO "artifact_id";
ALTER TABLE "ArtifactExtraction" RENAME COLUMN "questionTemplateId" TO "question_template_id";
ALTER TABLE "ArtifactExtraction" RENAME COLUMN "extractedValue" TO "extracted_value";
ALTER TABLE "ArtifactExtraction" RENAME COLUMN "evidenceSnippet" TO "evidence_snippet";
ALTER TABLE "ArtifactExtraction" RENAME COLUMN "extractedAt" TO "extracted_at";
ALTER TABLE "ArtifactExtraction" RENAME TO "artifact_extraction";

-- Recommendation -> recommendation
ALTER TABLE "Recommendation" RENAME COLUMN "sessionId" TO "session_id";
ALTER TABLE "Recommendation" RENAME COLUMN "argumentAcceptability" TO "argument_acceptability";
ALTER TABLE "Recommendation" RENAME COLUMN "orientationText" TO "orientation_text";
ALTER TABLE "Recommendation" RENAME COLUMN "blockerDiagnosis" TO "blocker_diagnosis";
ALTER TABLE "Recommendation" RENAME COLUMN "vetosTriggered" TO "vetos_triggered";
ALTER TABLE "Recommendation" RENAME COLUMN "generatedAt" TO "generated_at";
ALTER TABLE "Recommendation" RENAME TO "recommendation";

-- Argument -> argument
ALTER TABLE "Argument" RENAME COLUMN "recommendationId" TO "recommendation_id";
ALTER TABLE "Argument" RENAME COLUMN "backingChunkIds" TO "backing_chunk_ids";
ALTER TABLE "Argument" RENAME COLUMN "defeatedBy" TO "defeated_by";
ALTER TABLE "Argument" RENAME COLUMN "suspendedByVeto" TO "suspended_by_veto";
ALTER TABLE "Argument" RENAME TO "argument";

-- LLMBenchmarkRecord -> llm_benchmark_record
ALTER TABLE "LLMBenchmarkRecord" RENAME COLUMN "experimentId" TO "experiment_id";
ALTER TABLE "LLMBenchmarkRecord" RENAME COLUMN "latencyMs" TO "latency_ms";
ALTER TABLE "LLMBenchmarkRecord" RENAME COLUMN "tokensIn" TO "tokens_in";
ALTER TABLE "LLMBenchmarkRecord" RENAME COLUMN "tokensOut" TO "tokens_out";
ALTER TABLE "LLMBenchmarkRecord" RENAME COLUMN "evaluationScore" TO "evaluation_score";
ALTER TABLE "LLMBenchmarkRecord" RENAME TO "llm_benchmark_record";

-- BenchmarkExperiment -> benchmark_experiment
ALTER TABLE "BenchmarkExperiment" RENAME COLUMN "candidateModels" TO "candidate_models";
ALTER TABLE "BenchmarkExperiment" RENAME COLUMN "testPrompts" TO "test_prompts";
ALTER TABLE "BenchmarkExperiment" RENAME COLUMN "evaluationCriteria" TO "evaluation_criteria";
ALTER TABLE "BenchmarkExperiment" RENAME COLUMN "winnerModel" TO "winner_model";
ALTER TABLE "BenchmarkExperiment" RENAME COLUMN "decisionRationale" TO "decision_rationale";
ALTER TABLE "BenchmarkExperiment" RENAME COLUMN "createdAt" TO "created_at";
ALTER TABLE "BenchmarkExperiment" RENAME COLUMN "completedAt" TO "completed_at";
ALTER TABLE "BenchmarkExperiment" RENAME TO "benchmark_experiment";

-- BenchmarkRun -> benchmark_run
ALTER TABLE "BenchmarkRun" RENAME COLUMN "experimentId" TO "experiment_id";
ALTER TABLE "BenchmarkRun" RENAME COLUMN "promptId" TO "prompt_id";
ALTER TABLE "BenchmarkRun" RENAME COLUMN "latencyMs" TO "latency_ms";
ALTER TABLE "BenchmarkRun" RENAME COLUMN "tokensIn" TO "tokens_in";
ALTER TABLE "BenchmarkRun" RENAME COLUMN "tokensOut" TO "tokens_out";
ALTER TABLE "BenchmarkRun" RENAME COLUMN "evaluationScore" TO "evaluation_score";
ALTER TABLE "BenchmarkRun" RENAME COLUMN "evaluationMethod" TO "evaluation_method";
ALTER TABLE "BenchmarkRun" RENAME COLUMN "evaluationNotes" TO "evaluation_notes";
ALTER TABLE "BenchmarkRun" RENAME COLUMN "ranAt" TO "ran_at";
ALTER TABLE "BenchmarkRun" RENAME TO "benchmark_run";

-- Rename PK/FK constraints and indexes to match snake_case convention
-- AlterTable
ALTER TABLE "answer" RENAME CONSTRAINT "Answer_pkey" TO "answer_pkey";
-- AlterTable
ALTER TABLE "argument" RENAME CONSTRAINT "Argument_pkey" TO "argument_pkey";
-- AlterTable
ALTER TABLE "artifact" RENAME CONSTRAINT "Artifact_pkey" TO "artifact_pkey";
-- AlterTable
ALTER TABLE "artifact_extraction" RENAME CONSTRAINT "ArtifactExtraction_pkey" TO "artifact_extraction_pkey";
-- AlterTable
ALTER TABLE "artifact_variable" RENAME CONSTRAINT "ArtifactVariable_pkey" TO "artifact_variable_pkey";
-- AlterTable
ALTER TABLE "benchmark_experiment" RENAME CONSTRAINT "BenchmarkExperiment_pkey" TO "benchmark_experiment_pkey";
-- AlterTable
ALTER TABLE "benchmark_run" RENAME CONSTRAINT "BenchmarkRun_pkey" TO "benchmark_run_pkey";
-- AlterTable
ALTER TABLE "collaborator" RENAME CONSTRAINT "Collaborator_pkey" TO "collaborator_pkey";
-- AlterTable
ALTER TABLE "conflict_definition" RENAME CONSTRAINT "ConflictDefinition_pkey" TO "conflict_definition_pkey";
-- AlterTable
ALTER TABLE "dimension_definition" RENAME CONSTRAINT "DimensionDefinition_pkey" TO "dimension_definition_pkey";
-- AlterTable
ALTER TABLE "domain_config" RENAME CONSTRAINT "DomainConfig_pkey" TO "domain_config_pkey";
-- AlterTable
ALTER TABLE "git_connection" RENAME CONSTRAINT "GitConnection_pkey" TO "git_connection_pkey";
-- AlterTable
ALTER TABLE "llm_benchmark_record" RENAME CONSTRAINT "LLMBenchmarkRecord_pkey" TO "llm_benchmark_record_pkey";
-- AlterTable
ALTER TABLE "profile" RENAME CONSTRAINT "Profile_pkey" TO "profile_pkey";
-- AlterTable
ALTER TABLE "profile_definition" RENAME CONSTRAINT "ProfileDefinition_pkey" TO "profile_definition_pkey";
-- AlterTable
ALTER TABLE "project" RENAME CONSTRAINT "Project_pkey" TO "project_pkey";
-- AlterTable
ALTER TABLE "question_instance" RENAME CONSTRAINT "QuestionInstance_pkey" TO "question_instance_pkey";
-- AlterTable
ALTER TABLE "question_template" RENAME CONSTRAINT "QuestionTemplate_pkey" TO "question_template_pkey";
-- AlterTable
ALTER TABLE "question_template_edge" RENAME CONSTRAINT "QuestionTemplateEdge_pkey" TO "question_template_edge_pkey";
-- AlterTable
ALTER TABLE "recommendation" RENAME CONSTRAINT "Recommendation_pkey" TO "recommendation_pkey";
-- AlterTable
ALTER TABLE "session" RENAME CONSTRAINT "Session_pkey" TO "session_pkey";
-- AlterTable
ALTER TABLE "veto_definition" RENAME CONSTRAINT "VetoDefinition_pkey" TO "veto_definition_pkey";
-- AlterTable
ALTER TABLE "warrant_definition" RENAME CONSTRAINT "WarrantDefinition_pkey" TO "warrant_definition_pkey";
-- RenameForeignKey
ALTER TABLE "answer" RENAME CONSTRAINT "Answer_artifactExtractionId_fkey" TO "answer_artifact_extraction_id_fkey";
-- RenameForeignKey
ALTER TABLE "answer" RENAME CONSTRAINT "Answer_collaboratorId_fkey" TO "answer_collaborator_id_fkey";
-- RenameForeignKey
ALTER TABLE "answer" RENAME CONSTRAINT "Answer_questionInstanceId_fkey" TO "answer_question_instance_id_fkey";
-- RenameForeignKey
ALTER TABLE "answer" RENAME CONSTRAINT "Answer_sessionId_fkey" TO "answer_session_id_fkey";
-- RenameForeignKey
ALTER TABLE "argument" RENAME CONSTRAINT "Argument_defeatedBy_fkey" TO "argument_defeated_by_fkey";
-- RenameForeignKey
ALTER TABLE "argument" RENAME CONSTRAINT "Argument_recommendationId_fkey" TO "argument_recommendation_id_fkey";
-- RenameForeignKey
ALTER TABLE "artifact" RENAME CONSTRAINT "Artifact_gitConnectionId_fkey" TO "artifact_git_connection_id_fkey";
-- RenameForeignKey
ALTER TABLE "artifact" RENAME CONSTRAINT "Artifact_projectId_fkey" TO "artifact_project_id_fkey";
-- RenameForeignKey
ALTER TABLE "artifact_extraction" RENAME CONSTRAINT "ArtifactExtraction_artifactId_fkey" TO "artifact_extraction_artifact_id_fkey";
-- RenameForeignKey
ALTER TABLE "artifact_extraction" RENAME CONSTRAINT "ArtifactExtraction_questionTemplateId_fkey" TO "artifact_extraction_question_template_id_fkey";
-- RenameForeignKey
ALTER TABLE "artifact_variable" RENAME CONSTRAINT "ArtifactVariable_domainConfigId_fkey" TO "artifact_variable_domain_config_id_fkey";
-- RenameForeignKey
ALTER TABLE "benchmark_run" RENAME CONSTRAINT "BenchmarkRun_experimentId_fkey" TO "benchmark_run_experiment_id_fkey";
-- RenameForeignKey
ALTER TABLE "collaborator" RENAME CONSTRAINT "Collaborator_profileId_fkey" TO "collaborator_profile_id_fkey";
-- RenameForeignKey
ALTER TABLE "collaborator" RENAME CONSTRAINT "Collaborator_projectId_fkey" TO "collaborator_project_id_fkey";
-- RenameForeignKey
ALTER TABLE "conflict_definition" RENAME CONSTRAINT "ConflictDefinition_domainConfigId_fkey" TO "conflict_definition_domain_config_id_fkey";
-- RenameForeignKey
ALTER TABLE "dimension_definition" RENAME CONSTRAINT "DimensionDefinition_domainConfigId_fkey" TO "dimension_definition_domain_config_id_fkey";
-- RenameForeignKey
ALTER TABLE "git_connection" RENAME CONSTRAINT "GitConnection_projectId_fkey" TO "git_connection_project_id_fkey";
-- RenameForeignKey
ALTER TABLE "llm_benchmark_record" RENAME CONSTRAINT "LLMBenchmarkRecord_experimentId_fkey" TO "llm_benchmark_record_experiment_id_fkey";
-- RenameForeignKey
ALTER TABLE "profile_definition" RENAME CONSTRAINT "ProfileDefinition_domainConfigId_fkey" TO "profile_definition_domain_config_id_fkey";
-- RenameForeignKey
ALTER TABLE "project" RENAME CONSTRAINT "Project_domainConfigId_fkey" TO "project_domain_config_id_fkey";
-- RenameForeignKey
ALTER TABLE "question_instance" RENAME CONSTRAINT "QuestionInstance_sessionId_fkey" TO "question_instance_session_id_fkey";
-- RenameForeignKey
ALTER TABLE "question_template" RENAME CONSTRAINT "QuestionTemplate_domainConfigId_fkey" TO "question_template_domain_config_id_fkey";
-- RenameForeignKey
ALTER TABLE "question_template_edge" RENAME CONSTRAINT "QuestionTemplateEdge_sourceTemplateId_fkey" TO "question_template_edge_source_template_id_fkey";
-- RenameForeignKey
ALTER TABLE "question_template_edge" RENAME CONSTRAINT "QuestionTemplateEdge_targetTemplateId_fkey" TO "question_template_edge_target_template_id_fkey";
-- RenameForeignKey
ALTER TABLE "recommendation" RENAME CONSTRAINT "Recommendation_sessionId_fkey" TO "recommendation_session_id_fkey";
-- RenameForeignKey
ALTER TABLE "session" RENAME CONSTRAINT "Session_projectId_fkey" TO "session_project_id_fkey";
-- RenameForeignKey
ALTER TABLE "veto_definition" RENAME CONSTRAINT "VetoDefinition_domainConfigId_fkey" TO "veto_definition_domain_config_id_fkey";
-- RenameForeignKey
ALTER TABLE "warrant_definition" RENAME CONSTRAINT "WarrantDefinition_dimensionId_fkey" TO "warrant_definition_dimension_id_fkey";
-- RenameForeignKey
ALTER TABLE "warrant_definition" RENAME CONSTRAINT "WarrantDefinition_domainConfigId_fkey" TO "warrant_definition_domain_config_id_fkey";
-- RenameIndex
ALTER INDEX "Answer_questionInstanceId_key" RENAME TO "answer_question_instance_id_key";
-- RenameIndex
ALTER INDEX "DimensionDefinition_domainConfigId_id_key" RENAME TO "dimension_definition_domain_config_id_id_key";
-- RenameIndex
ALTER INDEX "DomainConfig_domainName_domainVersion_key" RENAME TO "domain_config_domain_name_domain_version_key";
-- RenameIndex
ALTER INDEX "ProfileDefinition_domainConfigId_id_key" RENAME TO "profile_definition_domain_config_id_id_key";
-- RenameIndex
ALTER INDEX "Recommendation_sessionId_key" RENAME TO "recommendation_session_id_key";
